### ISSUE TITLE
Authentication error [code: 10000]

### ISSUE THREAD

**Issue by Barandehyebazi** [bepass-org/tunl#19]
![image](https://github.com/user-attachments/assets/ed164b1f-a976-4ef9-9cca-df4920686b9e)

**Comment by unclejacki** [comment]
I'ts related to your cf token, not tunl. two ways to solve your problem:

1. you need to give your token enough [permissions](https://developers.cloudflare.com/fundamentals/api/reference/permissions/). as it says, visit https://dash.cloudflare.com/profile/api-tokens and make sure it has `User Details` Read permission.

![2024:07:15:08:46:14](https://github.com/user-attachments/assets/b020f096-ef0e-4737-8cfb-eae750ea2d50)

2. Also when you create a new token, cloudflare provides predefined templates you can use:

![2024:07:15:08:47:51](https://github.com/user-attachments/assets/d2de6252-16d7-4457-85f1-36ac0d851f5d)
