### ISSUE TITLE
Could I add a Domain?

### ISSUE THREAD

**Issue by Barandehyebazi** [bepass-org/tunl#20]
I have a domain which I wanna connect it to the worker 
I installed the domain as Subdomain and Route but it doesn't work ?
is there any way?

**Comment by unclejacki** [comment]
You probably need to specify your domain inside `wrangler.toml`. please take a look at:
https://developers.cloudflare.com/workers/configuration/routing/custom-domains/#set-up-a-custom-domain-in-your-wranglertoml
